apiVersion: v1
kind: Service
metadata:
 name: etcd-svc
spec:
 ports:
 - port: 2379
   name: tcp2379
   protocol: TCP
   targetPort: 2379
 - port: 2380
   name: tcp2380
   protocol: TCP
   targetPort: 2380
 selector:
   app: etcd
 type: ClusterIP
